version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/var/lib/mongodb"
  mo2:
    image: registry.cn-hangzhou.aliyuncs.com/mo2/mo2:latest
    env_file:
      - var.env
    environment:
      - qiniuak=${qiniuak}
      - qiniusk=${qiniusk}
    ports:
      - 5001:5001
    depends_on:
      - "mongodb"

volumes:
  mongodata:
