version: "3.4"
services:
  mongodb:
    image: mongo
    volumes:
      - "./mongo-volume:/data/db"
  redis:
    image: "bitnami/redis"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  mo2:
    image: registry.cn-hangzhou.aliyuncs.com/mo2/mo2:latest
    env_file:
      - var.env
    environment:
      - qiniuak=${qiniuak}
      - qiniusk=${qiniusk}
      - emailAddr=${emailAddr}
      - emailPass=${emailPass}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - "mongodb"
      - "redis"
    volumes:
      - "./secrets:/app/secrets"
  nginx:
    build: .
    ports:
      - 80:80
